### ISSUE TITLE
Need help with error handling

### ISSUE THREAD

**Issue by AMD-NICK** [lunarmodules/copas#138] opened 2022-09-12 19:18 UTC
## Copas 4.2.0

My script should perform HTTP requests to API 24/7 (about 1000 requests per minute), but after some time (sometimes after an hour, sometimes after several days) in the global error handler appears error `{"timeout"}`. Not as a string, but as a table.

## Timeout error location

The code from the file launcher.lua, through which my scripts (Telegram bots) are launched:

```lua
local res,err = pcall(copas.loop, function()
	print("Started")

	copas.setErrorHandler(function(msg, co)
		-- msg = {"timeout"}
		-- tostring(co) = "(thread) thread: 0x55ada1cb5e0"
		logger(msg, co)
	end, true)
end)

...
```

## Executing HTTP request

Simplified view of the function

```lua
local copas_request = require("copas.http").request

function http_request(tParams, fSuccess, fError)
	copas.addthread(function()
		copas.setErrorHandler(function(err, thread)
			-- handles errors like TLS/SSL handshake failed: timeout
			-- Everything works fine here
			timer_Simple(60, function() http_request(tParams, fSuccess, fError) end)
		end)

		local res, code, headers = copas_request(tParams)
		if res then fSuccess(code, res, headers) else fError(code) end
	end)
end
```

In the `http_request()` function, the errors are handled normally. Nowhere else is `copas.addthread` used, but an error `{"timeout"}` appears in the global handler. After this error appears, the execution of http requests starts to fall apart.

## Examples of tracebacks:

From the global error handler.

```log
2022-09-12 12:25:46 /home/ubuntu/.luarocks/share/lua/5.1/coxpcall.lua:79: attempt to call upvalue 'f' (a nil value)
stack traceback:
        /home/ubuntu/.luarocks/share/lua/5.1/coxpcall.lua:79: in function </home/ubuntu/.luarocks/share/lua/5.1/coxpcall.lua:79>
stack traceback:
        launcher.lua:109: in function <launcher.lua:108>
        (tail call): ?
        /home/ubuntu/.luarocks/share/lua/5.1/coxpcall.lua:47: in function </home/ubuntu/.luarocks/share/lua/5.1/coxpcall.lua:45>
        (tail call): ?
        (tail call): ?
        ...e/ubuntu/.luarocks/share/lua/5.1/timerwheel/init.lua:136: in function 'step'
        /home/ubuntu/.luarocks/share/lua/5.1/copas.lua:1211: in function </home/ubuntu/.luarocks/share/lua/5.1/copas.lua:1208>
        (tail call): ?

2022-09-12 12:27:10 ["timeout"]
stack traceback:
        launcher.lua:109: in function <launcher.lua:108>
        [C]: in function 'oldpcall'
        /home/ubuntu/.luarocks/share/lua/5.1/coxpcall.lua:68: in function </home/ubuntu/.luarocks/share/lua/5.1/coxpcall.lua:64>
        (tail call): ?
        /home/ubuntu/.luarocks/share/lua/5.1/copas.lua:1041: in function '_doTick'
        /home/ubuntu/.luarocks/share/lua/5.1/copas.lua:1332: in function 'step'
        /home/ubuntu/.luarocks/share/lua/5.1/copas.lua:1424: in function 'step'
        /home/ubuntu/.luarocks/share/lua/5.1/copas.lua:1460: in function </home/ubuntu/.luarocks/share/lua/5.1/copas.lua:1452>
        [C]: in function 'pcall'
        launcher.lua:102: in main chunk
        [C]: ?
```

**The question is, how to make the script fail-safe to such problems?** 🤔

---

P.S. Thank you very much for your work on copas. I'm a bit of a cheapskate, but if there was a "Donate" button here, I'd use it ❤️

**Comment by Tieske** [comment] 2022-09-12 21:12
did this also happen on previous versions of Copas?

**Comment by Tieske** [comment] 2022-09-14 12:38
you're using Lua 5.1, which has a bunch of workarounds for socket and (x)pcalls
see: https://github.com/lunarmodules/copas/blob/master/src/copas.lua#L31-L33 and https://github.com/lunarmodules/copas/blob/master/src/copas.lua#L35-L62

Any way of creating a small example that fails? considering the error, my impression is that it gets a timeout during the http request and then it fails.

**Comment by Tieske** [comment] 2022-09-14 12:39
btw Lua 5.1, but PuC Lua or LuaJIT? got an exact version? and possibly compile time compatibility flags used?

**Comment by Tieske** [comment] 2022-09-14 15:13
what type of requests are you making with the http client? simple small request/responses, or large payload, chunked or even streaming?

**Comment by Tieske** [comment] 2022-09-14 15:14
if you set up a small server in copas itself, that on each request adds a slightly longer delay. Then start a loop making requests, then it will at some point fail the request with a timeout. That might reproduce it.

**Comment by AMD-NICK** [comment] 2022-09-14 15:20
> what type of requests are you making with the http client? simple small request/responses, or large payload, chunked or even streaming?

Sending (I think) about 500 photos per day via Telegram API. But most http requests are relatively small json payloads

**Comment by Tieske** [comment] 2022-09-18 12:07
Any updates? How did it work with Lua 5.4? I think I sort a reproduced the issue in #138 , which only fails on Lua 5.1. So if I'm correct your 5.4 tests should just work, without the issue.

**Comment by AMD-NICK** [comment] 2022-09-19 15:27
Since Issue was published, I've highly optimized the code to perform far fewer http requests, and during active development I often restarted the script, which eliminated memory leaks as a theoretical reason of crashes

No error appeared during this period, but I'll keep watching

---

Of interest: my script works inside the GNU screen, where there are combinations of `Ctrl + A + [` (copy mode). In this mode stdout stops and you can search the logs. If you don't leave this mode for a few seconds you can catch such errors:

```
{   
    [1] = "copas.setErrorHandler GLOBAL",
    [2] = "attempt to call a nil value",
    [4] = "stack traceback:\n   launcher.lua:99: in function <launcher.lua:98>\n        (...tail calls...)\n    [C]: in function 'coxpcall.xpcall'\n    ...ver/luarocks/3.9.1_5.4/share/lua/5.4/timerwheel/init.lua:136: in method 'step'\n  ...buntu/.luaver/luarocks/3.9.1_5.4/share/lua/5.4/copas.lua:1211: in function <...buntu/.luaver/luarocks/3.9.1_5.4/share/lua/5.4/copas.lua:1208>\n   (...tail calls...)",
}

stack traceback:
   launcher.lua:99: in function <launcher.lua:98>
        (...tail calls...)
    [C]: in function 'coxpcall.xpcall'
    ...ver/luarocks/3.9.1_5.4/share/lua/5.4/timerwheel/init.lua:136: in method 'step'
    ...buntu/.luaver/luarocks/3.9.1_5.4/share/lua/5.4/copas.lua:1211: in function <...buntu/.luaver/luarocks/3.9.1_5.4/share/lua/5.4/copas.lua:1208>
   (...tail calls...)
```

... and "closed" error in http request function too.

demonstration: https://imgur.com/a/hjxiEu6

handler in launcher.lua:

<img width="456" alt="screenshot_2022-09-19_13 59 27@2x" src="https://user-images.githubusercontent.com/9200174/191003154-275ead4d-9327-4865-8941-642040d52aef.png">

---

This is not quite on topic, but I also noticed that if you do a lot (not exactly how many) http requests in short time, the script can "freeze" for a few seconds, and then throw the error "temporary failure in name resolution" or "host or service not provided or not known" in http request function.

**This is fixed by adding the domain to /etc/hosts**

freezing and error demonstration: https://imgur.com/a/a71thZr

**Comment by Tieske** [comment] 2022-09-19 19:03
> This is not quite on topic, but I also noticed that if you do a lot (not exactly how many) http requests in short time, the script can "freeze" for a few seconds, and then throw the error "temporary failure in name resolution" or "host or service not provided or not known" in http request function.

That's because for DNS luasocket underlying uses the system resolver, and hence those calls are blocking. This is known. This would require a Lua native dns resolver to fix. (low priority)

> Some requests are sent to my long polling server (similar to Telegram's getUpdates, if you know). There the connection is held for 30 seconds and repeated if there were no updates in this period
> 
> Simply put, some connections are held for a relatively long period of time

Separate timeouts can be set for send/receive/connect. You can use this to update the timeout. The default timeout in the http request is 30 seconds. See this code in my Server-Sent events client:

- changing the timeouts dynamically: https://github.com/Tieske/copas-sse/blob/main/src/copas-sse/client.lua#L214-L220
- but it requires access to the socket, which is collected here: https://github.com/Tieske/copas-sse/blob/main/src/copas-sse/client.lua#L373-L382

This will work only from 4.1 onwards, It's quite ugly. The http client needs a rewrite.

**Comment by Tieske** [comment] 2022-09-19 19:10
> No timeout error appeared during this period, but I'll keep watching

What Lua version is this now? still 5.1 PuC Rio, or something else?

**Comment by Tieske** [comment] 2022-09-19 19:41
PS. I just pushed version 4.3.0, please update to that version, it has some serious fixes (also timeout related).

The error with the `{"timeout"}` error (message wrapped in a table), hasn't been fixed, but only applies to PuC Lua 5.1.

**Comment by Tieske** [comment] 2022-09-21 13:47
Issue fixed. Released in 4.3.1.

Please give it a try with PuC Lua 5.1, and let me know if you run into any additional issues.

**Comment by AMD-NICK** [comment] 2022-10-01 21:53
![screenshot_2022-10-02_00 46 54](https://user-images.githubusercontent.com/9200174/193429582-106246ec-3994-4c0e-ac92-924480da6734.gif)

Nearly 9 million HTTP requests are behind us. The script has not crashed yet. I think the problem is solved.

Tested with `LuaJIT 2.0.5`

I will additional test this with Lua 5.1

**Comment by AMD-NICK** [comment] 2022-10-02 13:42
Copas 4.3.1

Crash after 356346 http requests (~8 hours of work, ~741 rqs/min):

> Stop working. Reason: ...u/.luaver/luarocks/3.9.1_5.1/share/lua/5.1/copas.lua:1455: bad argument #1 to 'min' (number expected, got nil)

<img width="630" alt="image" src="https://user-images.githubusercontent.com/9200174/193457019-3024f6bd-b6dd-4099-8824-da98e0baf7e1.png">

The problem appeared in this code block:

<img width="485" alt="screenshot_2022-10-02_16 40 28@2x" src="https://user-images.githubusercontent.com/9200174/193457134-0e12db37-17ef-4e17-8ea1-ce91080986fc.png">

Should I create new issue?

**Comment by Tieske** [comment] 2022-10-03 10:55
no need, let's continue here. Thx for testing!

The error can only happen if `_sleeping.getnext()` returns `nil`. Considering that code:

https://github.com/lunarmodules/copas/blob/154ec40086f2aefda3c32cc6febd6f4fc938fadb/src/copas.lua#L251-L257

it means `heap:peekValue()` returned `nil`, and the timer heap is empty. This should never be the case, because there will always be the `copas_core_timer` in the timer queue;

https://github.com/lunarmodules/copas/blob/154ec40086f2aefda3c32cc6febd6f4fc938fadb/src/copas.lua#L1245-L1251

So it seems the `copas_core_timer` task exited for some reason.

**Comment by AMD-NICK** [comment] 2022-10-03 12:26
Found this error:

```

2022-10-02 08:52:42 ...u/.luaver/luarocks/3.9.1_5.1/share/lua/5.1/copas.lua:1546: expected arg #1 to be a coroutine or nil
...u/.luaver/luarocks/3.9.1_5.1/share/lua/5.1/copas.lua:1546: expected arg #1 to be a coroutine or nil (coroutine: copas_core_timer, socket: nil)
stack traceback:
	[C]: in function 'assert'
	...u/.luaver/luarocks/3.9.1_5.1/share/lua/5.1/copas.lua:1546: in function 'getthreadname'
	...u/.luaver/luarocks/3.9.1_5.1/share/lua/5.1/copas.lua:1000: in function 'gettraceback'
	./tlib/init.lua:13: in function <./tlib/init.lua:12>
	(tail call): ?
	(tail call): ?
	...luaver/luarocks/3.9.1_5.1/share/lua/5.1/coxpcall.lua:47: in function <...luaver/luarocks/3.9.1_5.1/share/lua/5.1/coxpcall.lua:45>
	(tail call): ?
	(tail call): ?
	...e/ubuntu/.luarocks/share/lua/5.1/timerwheel/init.lua:136: in function 'step'
	...u/.luaver/luarocks/3.9.1_5.1/share/lua/5.1/copas.lua:1248: in function <...u/.luaver/luarocks/3.9.1_5.1/share/lua/5.1/copas.lua:1245>
	(tail call): ?

```

**Comment by Tieske** [comment] 2022-10-03 13:28
yes, that error is the one that kills the `copas_core_timer` task, and then the follow up errors cause the loop to break.

The issue is with coxpcall, but worked around it in #146 .

This will only fix the breaking of the loop. Somewhere there is an bug in a timeout-callback that is obfuscated by this one. So once this is fixed, you'll probably see the real underlying error in the logs.

**Comment by Tieske** [comment] 2022-10-03 13:34
just pushed version 4.3.2, containing the errorhandler fix. Please give it another spin. Really interested in the underlying error

**Comment by Tieske** [comment] 2022-10-04 11:32
so yesterday I did some stress testing and ran into the following error;
```
/usr/local/share/lua/5.1/coxpcall.lua:79: attempt to call upvalue 'f' (a nil value)
```
Which seems to be the same error that was reported initially.

This was a bug in the timerwheel, used my lunch break for the fix: [Tieske/timerwheel.lua@`0b84566` (#6)](https://github.com/Tieske/timerwheel.lua/pull/6/commits/0b845665dea12258230837db754fd6d7bf923fb5)

Just install the newer version of timerwheel (`1.0.1`, over `1.0.0`);
```
$ luarocks install timerwheel
```

That should finally fix this issue all together. Please reopen if the issue reappears.

**Closed by Tieske** 2022-10-04 11:32 UTC
